package com.befitnessapp.ui.localization

import androidx.compose.runtime.staticCompositionLocalOf
import com.befitnessapp.prefs.AppLanguage

data class HomeStrings(
    val title: String,
    val todayPrefix: String,
    val weeklyVolumeTitle: String,
    val weeklyPrsTitle: String,
    val weeklyRepsTitle: String,
    val weeklySetsTitle: String,
    val weeklyProgressTitle: String,
    val weeklyProgressValue: (String, String) -> String,
    val quickActionsTitle: String,
    val actionAddWorkoutTitle: String,
    val actionAddWorkoutSubtitle: String,
    val actionCalendarTitle: String,
    val actionCalendarSubtitle: String,
    val actionLibraryTitle: String,
    val actionLibrarySubtitle: String,
    val actionRoutinesTitle: String,
    val actionRoutinesSubtitle: String,
    val actionMuscleMapTitle: String,
    val actionMuscleMapSubtitle: String,
    val actionProfileTitle: String,
    val actionProfileSubtitle: String,
    val actionRecommendationsTitle: String,
    val actionRecommendationsSubtitle: String,
    val actionSettingsTitle: String,
    val actionSettingsSubtitle: String,
    val lastWorkoutTitle: String,
    val lastWorkoutEmpty: String,
    val lastWorkoutInfo: (String, String, Int, Int) -> String,
    val lastWorkoutHistoryButton: String,
    val musclePreviewTitle: String,
    val musclePreviewHint: String,
    val recentsTitle: String,
    val recentsSeeCalendarButton: String,
    val recentsItemInfo: (String, Int, Int) -> String
)

data class SettingsStrings(
    val title: String,
    val backButtonContentDescription: String,
    val languageSectionTitle: String,
    val languageEsLabel: String,
    val languageEnLabel: String,
    val themeSectionTitle: String,
    val themeSystemLabel: String,
    val themeLightLabel: String,
    val themeDarkLabel: String,
    val unitsSectionTitle: String,
    val unitsKgLabel: String,
    val unitsLbLabel: String,
    val weeklyGoalSectionTitle: String,
    val weeklyGoalHint: String,
    val weeklyGoalSaveButton: String,
    val weeklyGoalSavedToast: String,
    val remindersSectionTitle: String,
    val remindersDescription: String
)

data class AddWorkoutStrings(
    val title: String,
    val datePrefix: String,
    val searchLabel: String,
    val filterAll: String,
    val loadRoutineButton: String,
    val viewSelectionButton: (Int) -> String,
    val noResults: String,
    val logButton: String,
    val sheetSetsTitle: String,
    val sheetRepsLabel: String,
    val sheetWeightLabel: (String) -> String,
    val sheetDeleteSetButton: String,
    val sheetAddSetButton: String,
    val sheetSaveChangesButton: String,
    val selectionTitle: (Int) -> String,
    val selectionEmpty: String,
    val selectionEditSetsButton: String,
    val selectionRemoveExerciseContentDescription: String,
    val routineDefaultName: String,
    val summaryTitle: String,
    val summaryVolumeTitle: String,
    val summaryRepsTitle: String,
    val summaryExercisesTitle: String,
    val summarySetsTitle: String,
    val summaryHighlightsTitle: String,
    val summaryPrsTitle: String,
    val summaryCloseButton: String
)

data class RoutinesStrings(
    val homeTitle: String,
    val homeBackButton: String,
    val homeQuestion: String,
    val homeMyRoutinesButton: String,
    val homeCreateNewButton: String,
    val listTitle: String,
    val listBackButton: String,
    val listEmptyText: String,
    val listEmptyCreateButton: String,
    val listCardFallbackName: String,
    val listCardExercisesLabel: String,
    val listCardTotalSetsLabel: String,
    val listOpenButton: String,
    val listDeleteButton: String,
    val listBottomBackButton: String,
    val listBottomCreateNewButton: String,
    val deleteDialogTitle: String,
    val deleteDialogText: String,
    val deleteDialogConfirm: String,
    val deleteDialogCancel: String,
    val builderNewTitle: String,
    val builderEditTitle: String,
    val builderDeleteButton: String,
    val builderBackButton: String,
    val builderNameLabel: String,
    val builderAddExerciseButton: String,
    val builderContentTitle: String,
    val builderEmptyExercises: String,
    val builderExerciseFallback: String,
    val builderRemoveExerciseButton: String,
    val builderSetsLabel: String,
    val builderCancelButton: String,
    val builderSaveNewButton: String,
    val builderSaveEditButton: String,
    val pickerTitle: String,
    val pickerSearchLabel: String,
    val pickerFilterAll: String,
    val pickerPatternPrefix: String,
    val pickerNoResults: String,
    val pickerCloseButton: String,
    val incompleteTitle: String,
    val incompleteText: String,
    val incompleteOkButton: String,
    val savedEmptyTitle: String,
    val savedEmptyCreateButton: String,
    val savedRowOpenButton: String,
    val savedRowArchiveButton: String
)

data class MuscleMapStrings(
    val topBarBackButton: String,
    val segmentedFront: String,
    val segmentedBack: String,
    val segmentedSide: String,
    val silhouetteFront: String,
    val silhouetteBack: String,
    val silhouetteSide: String,
    val silhouettePlaceholderSuffix: String,
    val coverageTitle: String,
    val coverageLabel: (Int) -> String,
    val coverageDeficitLabel: (Int) -> String,
    val legend0to40: String,
    val legend40to70: String,
    val legend70to100: String,
    val legend100to120: String,
    val legend120Plus: String,
    val fullBackButton: String
)

data class LogStrings(
    val title: String,
    val emptyText: String,
    val backButton: String,
    val datePrefix: String,
    val notesPrefix: String,
    val repsWeightFormat: (Int, Float) -> String
)

data class RecommendationsStrings(
    val title: String,
    val subtitle: String,
    val allCoveredTitle: String,
    val allCoveredText: String,
    val priorityLabel: (String) -> String,
    val deficitChipLabel: (String, Int) -> String,
    val backButton: String
)

data class ProfileStrings(
    val title: String,
    val backButtonContentDescription: String,
    val accountSectionTitle: String,
    val accountNameLabel: String,
    val accountEmailLabel: String,
    val accountSourceLabel: String,
    val emptyStatsTitle: String,
    val emptyStatsText: String,
    val emptyStatsHint: String,
    val summaryTitle: String,
    val totalWorkoutsLabel: String,
    val totalVolumeLabel: String,
    val totalSetsLabel: String,
    val totalRepsLabel: String,
    val streaksTitle: String,
    val bestStreakLabel: String,
    val currentStreakLabel: String,
    val streaksInfo: String
)

data class AppStrings(
    val home: HomeStrings,
    val settings: SettingsStrings,
    val addWorkout: AddWorkoutStrings,
    val routines: RoutinesStrings,
    val muscleMap: MuscleMapStrings,
    val log: LogStrings,
    val recommendations: RecommendationsStrings,
    val profile: ProfileStrings
)

val LocalStrings = staticCompositionLocalOf<AppStrings> {
    error("AppStrings not provided")
}

private val EsAppStrings = AppStrings(
    home = HomeStrings(
        title = "Tu semana de entrenamiento",
        todayPrefix = "Hoy",
        weeklyVolumeTitle = "Volumen (sem)",
        weeklyPrsTitle = "PRs (sem)",
        weeklyRepsTitle = "Reps (sem)",
        weeklySetsTitle = "Sets (sem)",
        weeklyProgressTitle = "Progreso de la semana",
        weeklyProgressValue = { done, goal -> "$done / $goal" },
        quickActionsTitle = "Acciones rápidas",
        actionAddWorkoutTitle = "Añadir entrenamiento",
        actionAddWorkoutSubtitle = "Crear un log rápido",
        actionCalendarTitle = "Calendario",
        actionCalendarSubtitle = "Ver días entrenados",
        actionLibraryTitle = "Biblioteca",
        actionLibrarySubtitle = "Buscar ejercicios",
        actionRoutinesTitle = "Rutinas",
        actionRoutinesSubtitle = "Tus rutinas guardadas",
        actionMuscleMapTitle = "Mapa muscular",
        actionMuscleMapSubtitle = "Vista por grupos",
        actionProfileTitle = "Perfil",
        actionProfileSubtitle = "Datos e idioma",
        actionRecommendationsTitle = "Recomendaciones",
        actionRecommendationsSubtitle = "Ideas para hoy",
        actionSettingsTitle = "Ajustes",
        actionSettingsSubtitle = "Tema y preferencias",
        lastWorkoutTitle = "Último entrenamiento",
        lastWorkoutEmpty = "Aún no registras entrenamientos.",
        lastWorkoutInfo = { date, volume, sets, reps ->
            "$date • Volumen: $volume · Sets: $sets · Reps: $reps"
        },
        lastWorkoutHistoryButton = "Ver historial",
        musclePreviewTitle = "Mapa muscular (preview)",
        musclePreviewHint = "Toca para ver el mapa completo",
        recentsTitle = "Recientes",
        recentsSeeCalendarButton = "Ver calendario",
        recentsItemInfo = { date, sets, reps ->
            "$date • Sets: $sets · Reps: $reps"
        }
    ),
    settings = SettingsStrings(
        title = "Ajustes",
        backButtonContentDescription = "Volver",
        languageSectionTitle = "Idioma",
        languageEsLabel = "Español",
        languageEnLabel = "English",
        themeSectionTitle = "Tema",
        themeSystemLabel = "Sistema",
        themeLightLabel = "Claro",
        themeDarkLabel = "Oscuro",
        unitsSectionTitle = "Unidades",
        unitsKgLabel = "kg",
        unitsLbLabel = "lb",
        weeklyGoalSectionTitle = "Meta semanal de volumen",
        weeklyGoalHint = "Ejemplo: 10 000 kg·rep",
        weeklyGoalSaveButton = "Guardar meta",
        weeklyGoalSavedToast = "Meta semanal actualizada",
        remindersSectionTitle = "Recordatorios",
        remindersDescription = "Activa notificaciones básicas de entrenamiento."
    ),
    addWorkout = AddWorkoutStrings(
        title = "Añadir ejercicio al workout",
        datePrefix = "Fecha:",
        searchLabel = "Buscar ejercicio",
        filterAll = "Todos",
        loadRoutineButton = "Cargar rutina",
        viewSelectionButton = { count -> "Ver selección ($count)" },
        noResults = "No se encontraron ejercicios.",
        logButton = "Loggear workout",
        sheetSetsTitle = "Sets",
        sheetRepsLabel = "Reps",
        sheetWeightLabel = { unit -> "Peso ($unit)" },
        sheetDeleteSetButton = "Eliminar",
        sheetAddSetButton = "Añadir set",
        sheetSaveChangesButton = "Guardar cambios",
        selectionTitle = { count -> "Tu selección ($count)" },
        selectionEmpty = "Aún no has añadido ejercicios.",
        selectionEditSetsButton = "Editar sets",
        selectionRemoveExerciseContentDescription = "Quitar ejercicio",
        routineDefaultName = "Entrenamiento",
        summaryTitle = "Resumen del workout",
        summaryVolumeTitle = "Volumen total",
        summaryRepsTitle = "Reps totales",
        summaryExercisesTitle = "Ejercicios",
        summarySetsTitle = "Sets",
        summaryHighlightsTitle = "Highlights",
        summaryPrsTitle = "Nuevos PRs",
        summaryCloseButton = "Cerrar"
    ),
    routines = RoutinesStrings(
        homeTitle = "Rutinas",
        homeBackButton = "Volver",
        homeQuestion = "¿Qué deseas hacer?",
        homeMyRoutinesButton = "Mis rutinas",
        homeCreateNewButton = "Crear nueva",
        listTitle = "Mis rutinas",
        listBackButton = "Volver",
        listEmptyText = "Aún no tienes rutinas. Crea una desde \"Crear nueva\".",
        listEmptyCreateButton = "Crear nueva",
        listCardFallbackName = "Rutina",
        listCardExercisesLabel = "Ejercicios",
        listCardTotalSetsLabel = "Sets totales",
        listOpenButton = "Editar / Abrir",
        listDeleteButton = "Borrar",
        listBottomBackButton = "Volver",
        listBottomCreateNewButton = "Crear nueva",
        deleteDialogTitle = "Borrar rutina",
        deleteDialogText = "¿Seguro que deseas borrar esta rutina? Esta acción no se puede deshacer.",
        deleteDialogConfirm = "Borrar",
        deleteDialogCancel = "Cancelar",
        builderNewTitle = "Nueva rutina",
        builderEditTitle = "Editar rutina",
        builderDeleteButton = "Borrar",
        builderBackButton = "Volver",
        builderNameLabel = "Nombre de la rutina",
        builderAddExerciseButton = "Agregar ejercicio",
        builderContentTitle = "Contenido",
        builderEmptyExercises = "Aún no has agregado ejercicios.",
        builderExerciseFallback = "Ejercicio",
        builderRemoveExerciseButton = "Eliminar",
        builderSetsLabel = "Sets:",
        builderCancelButton = "Cancelar",
        builderSaveNewButton = "Guardar",
        builderSaveEditButton = "Guardar cambios",
        pickerTitle = "Elegir ejercicio",
        pickerSearchLabel = "Buscar",
        pickerFilterAll = "Todos",
        pickerPatternPrefix = "Patrón:",
        pickerNoResults = "No se encontraron ejercicios.",
        pickerCloseButton = "Cerrar",
        incompleteTitle = "Rutina incompleta",
        incompleteText = "Añade un nombre y al menos un ejercicio con 1 set.",
        incompleteOkButton = "Ok",
        savedEmptyTitle = "Aún no tienes rutinas guardadas.",
        savedEmptyCreateButton = "Crear rutina",
        savedRowOpenButton = "Abrir",
        savedRowArchiveButton = "Archivar"
    ),
    muscleMap = MuscleMapStrings(
        topBarBackButton = "Atrás",
        segmentedFront = "Frente",
        segmentedBack = "Espalda",
        segmentedSide = "Perfil",
        silhouetteFront = "Vista frontal",
        silhouetteBack = "Vista posterior",
        silhouetteSide = "Vista lateral",
        silhouettePlaceholderSuffix = "(placeholder)",
        coverageTitle = "Cobertura (14 días)",
        coverageLabel = { p -> "Cobertura: $p%" },
        coverageDeficitLabel = { p -> "Cobertura: $p% (déficit)" },
        legend0to40 = "0–40%",
        legend40to70 = "40–70%",
        legend70to100 = "70–100%",
        legend100to120 = "100–120%",
        legend120Plus = "120%+",
        fullBackButton = "Volver"
    ),
    log = LogStrings(
        title = "Historial de entrenos",
        emptyText = "Aún no registras entrenos. Empieza en \"Agregar entrenamiento\".",
        backButton = "Volver",
        datePrefix = "Fecha:",
        notesPrefix = "Notas:",
        repsWeightFormat = { reps, weight -> "• $reps reps · peso $weight" }
    ),
    recommendations = RecommendationsStrings(
        title = "Recomendaciones (equilibrio 14 días)",
        subtitle = "Priorizamos los músculos con menor cobertura vs. tu meta semanal.",
        allCoveredTitle = "¡Todo cubierto por ahora!",
        allCoveredText = "Loggea más entrenos para personalizar mejor las sugerencias.",
        priorityLabel = { score -> "Prioridad: $score" },
        deficitChipLabel = { name, percent -> "$name • $percent%" },
        backButton = "Volver"
    ),
    profile = ProfileStrings(
        title = "Perfil",
        backButtonContentDescription = "Volver",
        accountSectionTitle = "Datos de la cuenta",
        accountNameLabel = "Nombre: Invitado",
        accountEmailLabel = "Correo: ---",
        accountSourceLabel = "Origen de datos: Local (demo)",
        emptyStatsTitle = "Resumen de entrenamiento",
        emptyStatsText = "Aún no has registrado entrenamientos.",
        emptyStatsHint = "Cuando loggees tus workouts, aquí verás tus estadísticas.",
        summaryTitle = "Resumen de entrenamiento",
        totalWorkoutsLabel = "Workouts totales",
        totalVolumeLabel = "Volumen total",
        totalSetsLabel = "Sets totales",
        totalRepsLabel = "Reps totales",
        streaksTitle = "Rachas",
        bestStreakLabel = "Mejor racha (días)",
        currentStreakLabel = "Racha actual",
        streaksInfo = "Se calcula en los últimos 12 meses."
    )
)

private val EnAppStrings = AppStrings(
    home = HomeStrings(
        title = "Your training week",
        todayPrefix = "Today",
        weeklyVolumeTitle = "Volume (wk)",
        weeklyPrsTitle = "PRs (wk)",
        weeklyRepsTitle = "Reps (wk)",
        weeklySetsTitle = "Sets (wk)",
        weeklyProgressTitle = "Week progress",
        weeklyProgressValue = { done, goal -> "$done / $goal" },
        quickActionsTitle = "Quick actions",
        actionAddWorkoutTitle = "Add workout",
        actionAddWorkoutSubtitle = "Create a quick log",
        actionCalendarTitle = "Calendar",
        actionCalendarSubtitle = "View trained days",
        actionLibraryTitle = "Library",
        actionLibrarySubtitle = "Search exercises",
        actionRoutinesTitle = "Routines",
        actionRoutinesSubtitle = "Your saved routines",
        actionMuscleMapTitle = "Muscle map",
        actionMuscleMapSubtitle = "Group view",
        actionProfileTitle = "Profile",
        actionProfileSubtitle = "Data and language",
        actionRecommendationsTitle = "Recommendations",
        actionRecommendationsSubtitle = "Ideas for today",
        actionSettingsTitle = "Settings",
        actionSettingsSubtitle = "Theme and preferences",
        lastWorkoutTitle = "Last workout",
        lastWorkoutEmpty = "You have not logged any workouts yet.",
        lastWorkoutInfo = { date, volume, sets, reps ->
            "$date • Volume: $volume · Sets: $sets · Reps: $reps"
        },
        lastWorkoutHistoryButton = "View history",
        musclePreviewTitle = "Muscle map (preview)",
        musclePreviewHint = "Tap to see full map",
        recentsTitle = "Recent",
        recentsSeeCalendarButton = "Open calendar",
        recentsItemInfo = { date, sets, reps ->
            "$date • Sets: $sets · Reps: $reps"
        }
    ),
    settings = SettingsStrings(
        title = "Settings",
        backButtonContentDescription = "Go back",
        languageSectionTitle = "Language",
        languageEsLabel = "Spanish",
        languageEnLabel = "English",
        themeSectionTitle = "Theme",
        themeSystemLabel = "System",
        themeLightLabel = "Light",
        themeDarkLabel = "Dark",
        unitsSectionTitle = "Units",
        unitsKgLabel = "kg",
        unitsLbLabel = "lb",
        weeklyGoalSectionTitle = "Weekly volume goal",
        weeklyGoalHint = "Example: 10 000 kg·rep",
        weeklyGoalSaveButton = "Save goal",
        weeklyGoalSavedToast = "Weekly goal updated",
        remindersSectionTitle = "Reminders",
        remindersDescription = "Enable basic training notifications."
    ),
    addWorkout = AddWorkoutStrings(
        title = "Add exercise to workout",
        datePrefix = "Date:",
        searchLabel = "Search exercise",
        filterAll = "All",
        loadRoutineButton = "Load routine",
        viewSelectionButton = { count -> "View selection ($count)" },
        noResults = "No exercises found.",
        logButton = "Log workout",
        sheetSetsTitle = "Sets",
        sheetRepsLabel = "Reps",
        sheetWeightLabel = { unit -> "Weight ($unit)" },
        sheetDeleteSetButton = "Remove",
        sheetAddSetButton = "Add set",
        sheetSaveChangesButton = "Save changes",
        selectionTitle = { count -> "Your selection ($count)" },
        selectionEmpty = "You have not added any exercises yet.",
        selectionEditSetsButton = "Edit sets",
        selectionRemoveExerciseContentDescription = "Remove exercise",
        routineDefaultName = "Workout",
        summaryTitle = "Workout summary",
        summaryVolumeTitle = "Total volume",
        summaryRepsTitle = "Total reps",
        summaryExercisesTitle = "Exercises",
        summarySetsTitle = "Sets",
        summaryHighlightsTitle = "Highlights",
        summaryPrsTitle = "New PRs",
        summaryCloseButton = "Close"
    ),
    routines = RoutinesStrings(
        homeTitle = "Routines",
        homeBackButton = "Back",
        homeQuestion = "What do you want to do?",
        homeMyRoutinesButton = "My routines",
        homeCreateNewButton = "Create new",
        listTitle = "My routines",
        listBackButton = "Back",
        listEmptyText = "You do not have routines yet. Create one from \"Create new\".",
        listEmptyCreateButton = "Create new",
        listCardFallbackName = "Routine",
        listCardExercisesLabel = "Exercises",
        listCardTotalSetsLabel = "Total sets",
        listOpenButton = "Edit / Open",
        listDeleteButton = "Delete",
        listBottomBackButton = "Back",
        listBottomCreateNewButton = "Create new",
        deleteDialogTitle = "Delete routine",
        deleteDialogText = "Are you sure you want to delete this routine? This action cannot be undone.",
        deleteDialogConfirm = "Delete",
        deleteDialogCancel = "Cancel",
        builderNewTitle = "New routine",
        builderEditTitle = "Edit routine",
        builderDeleteButton = "Delete",
        builderBackButton = "Back",
        builderNameLabel = "Routine name",
        builderAddExerciseButton = "Add exercise",
        builderContentTitle = "Content",
        builderEmptyExercises = "You have not added any exercises yet.",
        builderExerciseFallback = "Exercise",
        builderRemoveExerciseButton = "Remove",
        builderSetsLabel = "Sets:",
        builderCancelButton = "Cancel",
        builderSaveNewButton = "Save",
        builderSaveEditButton = "Save changes",
        pickerTitle = "Choose exercise",
        pickerSearchLabel = "Search",
        pickerFilterAll = "All",
        pickerPatternPrefix = "Pattern:",
        pickerNoResults = "No exercises found.",
        pickerCloseButton = "Close",
        incompleteTitle = "Incomplete routine",
        incompleteText = "Add a name and at least one exercise with 1 set.",
        incompleteOkButton = "Ok",
        savedEmptyTitle = "You do not have saved routines yet.",
        savedEmptyCreateButton = "Create routine",
        savedRowOpenButton = "Open",
        savedRowArchiveButton = "Archive"
    ),
    muscleMap = MuscleMapStrings(
        topBarBackButton = "Back",
        segmentedFront = "Front",
        segmentedBack = "Back",
        segmentedSide = "Side",
        silhouetteFront = "Front view",
        silhouetteBack = "Back view",
        silhouetteSide = "Side view",
        silhouettePlaceholderSuffix = "(placeholder)",
        coverageTitle = "Coverage (14 days)",
        coverageLabel = { p -> "Coverage: $p%" },
        coverageDeficitLabel = { p -> "Coverage: $p% (deficit)" },
        legend0to40 = "0–40%",
        legend40to70 = "40–70%",
        legend70to100 = "70–100%",
        legend100to120 = "100–120%",
        legend120Plus = "120%+",
        fullBackButton = "Back"
    ),
    log = LogStrings(
        title = "Workout log",
        emptyText = "You have not logged workouts yet. Start in \"Add workout\".",
        backButton = "Back",
        datePrefix = "Date:",
        notesPrefix = "Notes:",
        repsWeightFormat = { reps, weight -> "• $reps reps · weight $weight" }
    ),
    recommendations = RecommendationsStrings(
        title = "Recommendations (14-day balance)",
        subtitle = "We prioritize muscles with lower coverage vs. your weekly goal.",
        allCoveredTitle = "Everything covered for now!",
        allCoveredText = "Log more workouts to refine your suggestions.",
        priorityLabel = { score -> "Priority: $score" },
        deficitChipLabel = { name, percent -> "$name • $percent%" },
        backButton = "Back"
    ),
    profile = ProfileStrings(
        title = "Profile",
        backButtonContentDescription = "Go back",
        accountSectionTitle = "Account details",
        accountNameLabel = "Name: Guest",
        accountEmailLabel = "Email: ---",
        accountSourceLabel = "Data source: Local (demo)",
        emptyStatsTitle = "Training summary",
        emptyStatsText = "You have not logged any workouts yet.",
        emptyStatsHint = "Once you log your workouts, you'll see your stats here.",
        summaryTitle = "Training summary",
        totalWorkoutsLabel = "Total workouts",
        totalVolumeLabel = "Total volume",
        totalSetsLabel = "Total sets",
        totalRepsLabel = "Total reps",
        streaksTitle = "Streaks",
        bestStreakLabel = "Best streak (days)",
        currentStreakLabel = "Current streak",
        streaksInfo = "Computed over the last 12 months."
    )
)

fun stringsForLanguage(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.ES -> EsAppStrings
        AppLanguage.EN -> EnAppStrings
    }
}
